### PR TITLE
Move to Symfony 4 and deploy with fabric

### PR DESCRIPTION
**Pull request by pyrech**
Note:
- The root directory is now `public/` instead of `web/`
- The web server need write access to `var/` directory instead of `cache/`
- You can add an `APP_ENV=prod` and `APP_SECRET=xxxx` env vars that nginx should pass to fpm

### CODE REVIEW

**Comment by ternel** [comment]
Thx. Need to upgrade my server >_<'

**Comment by ternel** [comment]
Thx for this awesome PR. Need rebase though 😬 

😗

**Comment by pyrech** [comment]
Done!

**Comment by ternel** [comment]
Thx. :coca:

**Comment by pyrech** [comment]
OH ❤️

**Pull request merged**
